### ISSUE TITLE
404 error if multibyte URL's are allowed.

### ISSUE THREAD

**Issue by darianno** [Martimiz/silverstripe-languageprefix#16]
When I added

URLSegmentFilter:
  default_allow_multibyte: true

to .yml file, I got 404 error if visiting multibyte URL, like this - for example: www.mydomain.com/ru/заглавная-страница

**Comment by Martimiz** [comment]
Please check that the URL works with Translatable enabled, but without the LanguagePrefix module...

Discussion here: http://www.silverstripe.org/community/forums/general-questions/show/101333?start=8

**Comment by Martimiz** [comment]
Could you send me a MySQL dump of your test database? That would give me the russian content, which I can't create myself. Also your default Translatable locale?

**Comment by darianno** [comment]
My default Translatable locale is en_US. MySQL dump you can download here: http://error.si/data/sql_dump.zip

**Comment by Martimiz** [comment]
Thanks, got it :)

**Comment by NightJar** [comment]
At a quick poke through I'd say this double escape is probably causing issues: https://github.com/Martimiz/silverstripe-languageprefix/blob/master/code/PrefixModelAsController.php#L74 - although the default charset is utf8 which should be fine, so I am not sure. But seems most likely since latin charsets likely won't be touched (since they're generally all lowercase numbers, letters, and hyphens anyway) which accounts for the majority of test cases (especially if transliterating).

The original ModelAsController uses sprintf to build a raw where clause to pass directly in, rather than using the orm, so needs the manual escape.

Alas I do not have a development environment on hand to debug this through.

**Comment by Martimiz** [comment]
@NightJar: you were right on target, thanks :)

@Darianno: Could you check if the latest commit to master fixes your problem, so I can close this as fixed?

**Comment by darianno** [comment]
@Martimiz: I have checked. URL's are now working perfectly. Thank you!

**Comment by Martimiz** [comment]
Fixed in 7bb01b52bbdd7a6a7e1519a2f068aa7b3f4ffeee
