### ISSUE TITLE
How to hide the main language prefix

### ISSUE THREAD

**Issue by achappard** [Martimiz/silverstripe-languageprefix#18]
Is it possible to hide the main language prefix ?
For example, if the main language of my site is English,  I would like url like `http://www.mysite.com/about-us` (wihout the prefix)  and for the translation into French: `http://www.mysite.com/fr/ a-propos.`

For now, I have two urls:
- `http://www.mysite.com/en/about-us`
- `http://www.mysite.com/fr/a-propos`

**Comment by Martimiz** [comment]
Hi achappard,
Late reply - I was on holiday :)
There is a  'no-prefix-for-default' branch that isa rc1 and should be working fine - see this thread

#7

Andreas tested it globally, but it would be a good idea to test it before You use it - especially in regard to what happens with old urls and redirections and stuff, because it has been largely rewritten. And if you do, please let me know.
